### ISSUE TITLE
Unable to export account: no time information in ""

### ISSUE THREAD

**Issue by mhenrixon** [precipice/campfire_export#11]
Some days I get the following error `Unable to export account: no time information in ""` and the download breaks.

Any ideas what is up with that?

**Comment by precipice** [comment]
Is there any more specific error message in `campfire/export_errors.txt`?

It looks to me like the problem is a missing `created-at` tag in an account XML block. Do you know if the account that's breaking is especially old or does it have anything else odd about it?
