### ISSUE TITLE
Unable to export account: can't modify frozen Fixnum

### ISSUE THREAD

**Issue by raid5** [precipice/campfire_export#20]
OS X 10.9.1
Ruby 2.0.0p353

**Comment by precipice** [comment]
Yeah, unfortunately I haven't tested with ruby 2. I believe there's a closed issue that might help?

-M

**Comment by precipice** [comment]
Yes, https://github.com/precipice/campfire_export/issues/19 might help.

-M

**Comment by raid5** [comment]
Thanks. I ended up just using ruby 1.9.3 and it worked great!

**Comment by precipice** [comment]
Glad to hear it.

-M
